/**
 * Spelling/Grammar correction API
 *
 * This API interfaces an Yfirlestur.is compatible service
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: info@grammatek.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.grammatek.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param text 
 * @param annotateUnparsedSentences 
 * @param suppressSuggestions 
 * @param ignoreWordlist 
 * @param ignoreRules 
 */
@Serializable
data class CorrectRequest (

    @SerialName(value = "text")
    val text: kotlin.String,

    @SerialName(value = "annotate_unparsed_sentences")
    val annotateUnparsedSentences: kotlin.Boolean = true,

    @SerialName(value = "suppress_suggestions")
    val suppressSuggestions: kotlin.Boolean = false,

    @SerialName(value = "ignore_wordlist")
    val ignoreWordlist: kotlin.collections.List<kotlin.String> = arrayListOf(),

    @SerialName(value = "ignore_rules")
    val ignoreRules: kotlin.collections.List<kotlin.String> = arrayListOf()

)

