/**
 * Spelling/Grammar correction API
 *
 * This API interfaces an Yfirlestur.is compatible service
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: info@grammatek.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.grammatek.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param ambiguity 
 * @param numChars 
 * @param numParsed 
 * @param numSentences 
 * @param numTokens 
 */
@Serializable
data class Stats (

    @SerialName(value = "ambiguity")
    val ambiguity: kotlin.Double? = null,

    @SerialName(value = "num_chars")
    val numChars: kotlin.Int? = null,

    @SerialName(value = "num_parsed")
    val numParsed: kotlin.Int? = null,

    @SerialName(value = "num_sentences")
    val numSentences: kotlin.Int? = null,

    @SerialName(value = "num_tokens")
    val numTokens: kotlin.Int? = null

)

