/**
 * Grammar correction API
 *
 * This API interfaces Yfirlestur.is/
 *
 * The version of the OpenAPI document: 0.1.0-oas3
 * Contact: info@grammatek.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.grammatek.apis

import java.io.IOException

import org.grammatek.models.YfirlesturResponse

import org.grammatek.infrastructure.ApiClient
import org.grammatek.infrastructure.ApiResponse
import org.grammatek.infrastructure.ClientException
import org.grammatek.infrastructure.ClientError
import org.grammatek.infrastructure.ServerException
import org.grammatek.infrastructure.ServerError
import org.grammatek.infrastructure.MultiValueMap
import org.grammatek.infrastructure.RequestConfig
import org.grammatek.infrastructure.RequestMethod
import org.grammatek.infrastructure.ResponseType
import org.grammatek.infrastructure.Success

class DevelopersApi(basePath: kotlin.String = org.grammatek.apis.DevelopersApi.Companion.defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://yfirlestur.is")
        }
    }

    /**
    * Correct grammar of text
    * 
    * @param text
    * @return YfirlesturResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun correctApiPost(text: kotlin.String) : YfirlesturResponse {
        val localVarResponse = correctApiPostWithHttpInfo(text = text)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as YfirlesturResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Correct grammar of text
    * 
    * @param text  
    * @return ApiResponse<YfirlesturResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun correctApiPostWithHttpInfo(text: kotlin.String) : ApiResponse<YfirlesturResponse?> {
        val localVariableConfig = correctApiPostRequestConfig(text = text)

        return request<Map<String, Any?>, YfirlesturResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation correctApiPost
    *
    * @param text  
    * @return RequestConfig
    */
    fun correctApiPostRequestConfig(text: kotlin.String) : RequestConfig<Map<String, Any?>> {
        val localVariableBody = mapOf("text" to text)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "application/x-www-form-urlencoded")
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/correct.api",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

}
