name: Android CI
on:
  push:
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: mideind/Yfirlestur
          path: "yfirlestur"
          ref: "dockerfile_development"
      - name: Docker build
        run: |
          if [ ! -f "./gunicorn_user.txt" ]; then
          echo 'root' > gunicorn_user.txt
          echo 'root' >> gunicorn_user.txt
          fi
          docker build -t yfirlestur:latest ./yfirlestur/
      - name: Docker run
        run: |
          docker run -d yfirlestur
      - name: Curl
        run: |
          curl localhost:5002/correct.api -d "text=hello"
        
  
