name: Android CI
on:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5002:5002
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
<<<<<<< HEAD
          repository: mideind/Yfirlestur
          path: "yfirlestur"
          ref: "dockerfile_development"
      - name: Docker build
        run: |
          if [ ! -f "./gunicorn_user.txt" ]; then
          echo 'root' > gunicorn_user.txt
          echo 'root' >> gunicorn_user.txt
          fi
<<<<<<< HEAD
<<<<<<< HEAD
      - name: "Run yfirlestur"
        run: |
          docker build -t yfirlestur .
      - uses: addnab/docker-run-action@v3
        with:
          image: yfirlestur:latest
          options: -dp 5002:5002
=======
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
=======
>>>>>>> Update build.yml
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
<<<<<<< HEAD
          tags: localhost:5002/name/yfirlestur:latest
<<<<<<< HEAD
      - uses: addnab/docker-run-action@v3
        with:
<<<<<<< HEAD
          image: name/yfirlestur:latest
>>>>>>> Update build.yml
=======
          image: localhost:5002/name/yfirlestur:latest
>>>>>>> Update build.yml
=======
      - name: Docker run
        run: |
          docker run localhost:5002/name/yfirlestur:latest
          
>>>>>>> Update build.yml
        
  build:
    needs: api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: "Build the app"
        run: |
          git submodule update --init
          ./gradlew assemble
          ./gradlew build -x test
      - name: "Run tests"
=======
          docker build -t yfirlestur:latest ./yfirlestur/
      - name: Docker run
        run: |
          docker run -dp 5002:5002 yfirlestur
      - name: Curl
>>>>>>> Update build.yml
=======
          tags: localhost:5002/name/app:latest
      -
        name: Inspect
>>>>>>> Update build.yml
        run: |
          docker buildx imagetools inspect localhost:5000/name/app:latest

        
  
