name: Android CI
on:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Yfirlestur Repo
        uses: actions/checkout@v3
        with:
          repository: mideind/Yfirlestur
          path: yfirlestur
          ref: "dockerfile_development"
      - uses: docker/build-push-action@v2
        with:
          context: ./yfirlestur/
          tags: yfirlestur:latest
          push: false
          load: true
      - uses: addnab/docker-run-action@v3
        with:
          options: -dp 5002:5002
          image: yfirlestur:latest
      - name: Curl
        run: |
          curl --tlsv1.2 localhost:5002/correct.api -d "text=hello"

        
  
