name: Android CI
on:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: mideind/Yfirlestur
          ref: "dockerfile_development"
      - uses: docker/build-push-action@v2
        with:
          tags: test-image:latest
          push: false
          load: true
      - uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: echo "hello world"

        
  
