name: Android CI
on:
  push:
jobs:
  api: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: mideind/Yfirlestur
          ref: "dockerfile_development"
      - name: "docker build"
        run: |
          if [ ! -f "./gunicorn_user.txt" ]; then
          echo 'root' > gunicorn_user.txt
          echo 'root' >> gunicorn_user.txt
          fi
      - name: "Run yfirlestur"
        run: |
          docker build -t yfirlestur .
      - uses: docker/build-push-action@v2
        with:
          tags: yfirlestur:latest
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: yfirlestur:latest
          options: -dp 5002:5002
        
  build:
    needs: api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: "Build the app"
        run: |
          git submodule update --init
          ./gradlew assemble
          ./gradlew build -x test
      - name: "Run tests"
        run: |
          ./gradlew test
      - name: Archive reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: archive-reports
          path: |
            app/build/reports/**/*
