name: Android CI
on:
  push:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
<<<<<<< HEAD
      - name: Checkout Yfirlestur Repo
        uses: actions/checkout@v3
        with:
          repository: mideind/Yfirlestur
          path: yfirlestur
          ref: dockerfile_development
      - name: Create Yfirlestur Dependencies
        run: |
          if [ ! -f "./gunicorn_user.txt" ]; then
          echo 'root' > yfirlestur/gunicorn_user.txt
          echo 'root' >> yfirlestur/gunicorn_user.txt
          fi
      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          context: ./yfirlestur/
          tags: yfirlestur:latest
          push: false
          load: true      
      - name: Run Docker
        run: |
          docker run -dp 5002:5002 yfirlestur:latest
=======
      - name: Checkout yfirlestur repo
        uses: actions/checkout@v3
        with:
          repository: mideind/Yfirlestur
          path: "yfirlestur"
          ref: "dockerfile_development"
      - name: "Build Yfirlestur"
        run: |
          docker build -t yfirlestur ./yfirlestur/
<<<<<<< HEAD
<<<<<<< HEAD
      - name: "Run Yfirlestur"
        run: |
          docker run -dp 5002:5002 yfirlestur
>>>>>>> Update build.yml
=======
          docker run -w /yfirlestur/ -dp 5002:5002 yfirlestur
>>>>>>> Update build.yml
=======
      - name: "Run Yfirlestur"
        run: |
          docker run -w ./yfirlestur/ -dp 5002:5002 yfirlestur
          docker run -w /yfirlestur/ -dp 5002:5002 yfirlestur
          cd yfirlestur 
          docker run -dp 5002:5002 yfirlestur
          cd ..
>>>>>>> Update build.yml
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: "Build the app"
        run: |
          git submodule update --init
          ./gradlew assemble
          ./gradlew build -x test
      - name: "Run tests"
        run: |
          ./gradlew test
      - name: Archive reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          path: |
            app/build/reports/**/*
      - name: Download reports
        uses: actions/download-artifact@v3.0.0
        with:
          path: |
            app/build/reports/**/*
            
