name: Android CI
on:
  push:
jobs:
<<<<<<< HEAD
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
      - name: Checkout Yfirlestur Repo
        uses: actions/checkout@v3
        with:
          repository: mideind/Yfirlestur
          path: yfirlestur
          ref: dockerfile_development
      - name: Create Yfirlestur Dependencies
        run: |
          if [ ! -f "./gunicorn_user.txt" ]; then
          echo 'root' > yfirlestur/gunicorn_user.txt
          echo 'root' >> yfirlestur/gunicorn_user.txt
          fi
      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          context: ./yfirlestur/
          tags: yfirlestur:latest
          push: false
          load: true      
      - name: Run Docker
        run: |
          docker run -dp 5002:5002 yfirlestur:latest
=======
      - name: Checkout yfirlestur repo
        uses: actions/checkout@v3
=======
>>>>>>> Update build.yml
=======
=======
  api: 
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
>>>>>>> Update build.yml
      - name: Checkout yfirlestur repo
=======
      - name: Checkout
>>>>>>> Update build.yml
        uses: actions/checkout@v3
>>>>>>> Update build.yml
        with:
          repository: mideind/Yfirlestur
          ref: "dockerfile_development"
<<<<<<< HEAD
<<<<<<< HEAD
      - name: "docker build"
        run: |
<<<<<<< HEAD
          docker build -t yfirlestur ./yfirlestur/
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
      - name: "Run Yfirlestur"
<<<<<<< HEAD
<<<<<<< HEAD
        run: |
<<<<<<< HEAD
          docker run -dp 5002:5002 yfirlestur
>>>>>>> Update build.yml
=======
          docker run -w /yfirlestur/ -dp 5002:5002 yfirlestur
>>>>>>> Update build.yml
=======
      - name: "Run Yfirlestur"
        run: |
<<<<<<< HEAD
          docker run -dp 5002:5002 yfirlestur
<<<<<<< HEAD
          cd ..
>>>>>>> Update build.yml
=======
>>>>>>> Update build.yml
=======
          docker run -dp 5002:5002 yfirlestur:latest
>>>>>>> Update build.yml
=======
          docker run -it --entrypoint /bin/bash -dp 5002:5002 yfirlestur:latest
>>>>>>> Update build.yml
=======
        uses: addnab/docker-run-action@v3
        with:
          image: yfirlestur:latest
          options: -dp 5002:5002
>>>>>>> Update build.yml
=======
        run: |
<<<<<<< HEAD
          /usr/bin/docker run -dp 5002:5002 yfirlestur
>>>>>>> Update build.yml
=======
          docker run yfirlestur:latest
>>>>>>> Update build.yml
=======
          docker run -it yfirlestur:latest
>>>>>>> Update build.yml
=======
=======
      - name: "docker build"
        run: |
>>>>>>> Update build.yml
          if [ ! -f "./gunicorn_user.txt" ]; then
          echo 'root' > gunicorn_user.txt
          echo 'root' >> gunicorn_user.txt
          fi
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
          docker build -t yfirlestur:latest ./yfirlestur/
<<<<<<< HEAD
          docker run -it -p 5002:5002 yfirlestur
>>>>>>> Update build.yml
=======
=======
          docker build -t yfirlestur:latest .
>>>>>>> Update build.yml
=======
          docker build -t yfirlestur:latest ./yfirlestur/
>>>>>>> Update build.yml
=======
          docker build -t yfirlestur:latest .
>>>>>>> Update build.yml
      - name: "docker run"
        run: |
<<<<<<< HEAD
<<<<<<< HEAD
          docker run -p 5002:5002 yfirlestur
>>>>>>> Update build.yml
=======
          docker run -dp 5002:5002 yfirlestur
<<<<<<< HEAD
>>>>>>> Update build.yml
=======
=======
          docker run -d yfirlestur
>>>>>>> Update build.yml
=======
=======
          docker build -t yfirlestur:latest .
<<<<<<< HEAD
>>>>>>> Update build.yml
      - name: "Docker build"
        uses: docker/build-push-action@v2
        with:
          tags: yfirlestur:latest
          push: false
=======
>>>>>>> Update build.yml
      - name: "Docker run"
        uses: addnab/docker-run-action@v3
        with:
          image: yfirlestur:latest
          run: |
            if [ ! -f "./gunicorn_user.txt" ]; then
            echo 'root' > gunicorn_user.txt
            echo 'root' >> gunicorn_user.txt
            fi
>>>>>>> Update build.yml
  build:
    needs: api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
>>>>>>> Update build.yml
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: "Build the app"
        run: |
          git submodule update --init
          ./gradlew assemble
          ./gradlew build -x test
      - name: "Run tests"
        run: |
          ./gradlew test
      - name: Archive reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          path: |
            app/build/reports/**/*
      - name: Download reports
        uses: actions/download-artifact@v3.0.0
        with:
          path: |
            app/build/reports/**/*
            
